# Generated by Django 5.0.1 on 2024-01-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
