# Generated by Django 5.0.1 on 2024-02-01 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0003_alter_usercourse_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='usercourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tango.usercourse'),
        ),
    ]
