# Generated by Django 5.0.1 on 2024-02-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0004_alter_payment_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
