# Generated by Django 5.0.1 on 2024-02-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0005_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
