# Generated by Django 5.0.1 on 2024-02-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0008_alter_course_name_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
