# Generated by Django 5.0.1 on 2024-02-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0009_couponcode_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
