# Generated by Django 5.0.1 on 2024-02-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0011_userprofile_userip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
