# Generated by Django 5.0.1 on 2024-02-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0012_alter_userprofile_userip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
