# Generated by Django 5.0.1 on 2024-02-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0013_alter_userprofile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=30, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tango.userprofile')),
            ],
        ),
    ]
