# Generated by Django 5.0.1 on 2024-02-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0014_iptrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='complete_chapter',
            field=models.BooleanField(default=False),
        ),
    ]
