# Generated by Django 5.0.1 on 2024-02-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0016_remove_userprofile_userip_questions_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='length',
            new_name='numbers_of_chapter',
        ),
        migrations.AddField(
            model_name='course',
            name='time_to_complete',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institude',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
