# Generated by Django 5.0.1 on 2024-02-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0017_rename_length_course_numbers_of_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tango.chapter'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tango.course'),
        ),
    ]
