# Generated by Django 5.0.1 on 2024-02-08 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0018_questions_chapter_alter_questions_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tango.chapter'),
        ),
    ]
