# Generated by Django 5.0.1 on 2024-02-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0019_answers_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='serial_number',
            field=models.IntegerField(default=1),
        ),
    ]
