# Generated by Django 5.0.1 on 2024-02-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0021_rename_serial_number_userprofile_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(upload_to='files/profile/'),
        ),
    ]
