# Generated by Django 5.0.1 on 2024-02-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0023_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
