# Generated by Django 5.0.1 on 2024-02-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0024_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
