# Generated by Django 5.0.1 on 2024-02-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0026_alter_usercourse_date_alter_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='date',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
