# Generated by Django 5.0.1 on 2024-02-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0027_alter_usercourse_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='date',
            new_name='complete_date',
        ),
    ]
