# Generated by Django 5.0.1 on 2024-02-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0029_remove_iptrack_profile_iptrack_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
