# Generated by Django 5.0.1 on 2024-02-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0032_remove_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.FileField(null=True, upload_to='files/videos/'),
        ),
    ]
